### ISSUE TITLE
Support for `Release` build mode

### ISSUE THREAD

**Issue by IvanGodinez21** [galatea21/poke_dart#1]
# Description

When I create the build in [`Release`](https://docs.flutter.dev/testing/build-modes#release) build mode, it doesn't work as expected, but when running in debug mode seems to work fine, maybe it requires a better support with `dart2js`.

> **Note**
> Methods seems to add and/or replace the API endpoint with `minified:e-w`, so it can be part of the problem
>
> Example:
> ❌ `https://pokeapi.co/api/v2/minified:e-w?limit=10&offset=0`
> ✔️ `https://pokeapi.co/api/v2/pokemon?limit=10&offset=0`

## Notes
- Only works for [`Debug`](https://docs.flutter.dev/testing/build-modes#debug) and [`Profile`](https://docs.flutter.dev/testing/build-modes#profile) build modes
- Tested on web and android platforms
## Screenshots

<table>
  <thead>
    <tr>
      <th colspan="2" style="text-align: center;">Mode</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th style="text-align: center;">Production</th>
      <th style="text-align: center;">Development</th>
    </tr>
    <tr>
      <td><img src="https://github.com/galatea21/dart_pokedex/assets/45635827/517da372-c31b-4a4c-8c42-519c26af81c2" alt="Dark card"></td>
      <td><img src="https://github.com/galatea21/dart_pokedex/assets/45635827/78af8beb-fb59-4317-b290-56f75af9452e" alt="Light card"></td>
    </tr>
  </tbody>
</table>

**Comment by ThiDinh21** [comment]
Hi, I have been able to reproduce the error on both Android and Web.

I haven't been able to figure out why the package doesn't work on the Web release version yet but on the Android side, I was able to make it work just by adding `<uses-permission android:name="android.permission.INTERNET"/>` to the `AndroidManifest.xml`  file inside the `<manifest>` tag.

I will update you if I came up with something,

**Comment by ThiDinh21** [comment]
Seems like [this line](https://github.com/galatea21/dart_pokedex/blob/13ae3248bf4a23457f32d786673b624772069d88/lib/src/base_endpoint.dart#L51) causes the issue. It seems like Flutter Web release version's minification messes with the Generic's name. 

I use the Class's name as part of the URL, so to fix this I will probably use a switch case to match all the classes. I will patch this in the next version.

**Comment by brunogabriel** [comment]
is it working in version 0.3.0?
